[package]
name = "gbm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gbm"
path = "src/lib.rs"
crate-type = ["lib"]


[build-dependencies]
bindgen = "0.68.1"