#![allow(dead_code)]
#![allow(non_camel_case_types)]

#[derive(Debug, Clone, Copy)]
pub enum ErrorKind {
    RAMEN_CARD_OPEN_FAILED,
    RAMEN_DISPLAY_RESOURCES_FAILED,
    RAMEN_DISPLAY_CONNECTORS_NOT_FOUND,
    RAMEN_CONNECTOR_ENCODER_NOT_FOUND,
    RAMEN_CONNECTOR_ENCODER_FAILED,
    RAMEN_CONNECTOR_ENCODER_CRTC_NOT_FOUND,
    RAMEN_CONNECTOR_ENCODER_CRTC_FAILED,

}