#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(non_camel_case_types)]
use logos::Logos;

#[derive(Logos, Debug, PartialEq, Clone)]
pub enum Token {
    #[error]
    ERROR,
    EOF,
    #[token("()")]
    VOID,
    #[token("char")]
    CHAR_T,
    #[token("string")]
    String,
    #[regex("[a-zA-Z]+", |lexer| lexer.slice().to_owned())]
    IDENT(String),
    #[token("i8")]
    I8,
    #[token("i16")]
    I16,
    #[token("i32")]
    I32,
    #[token("i64")]
    I64,
    #[token("u8")]
    U8,
    #[token("u16")]
    U16,
    #[token("u32")]
    U32,
    #[token("u64")]
    U64,
    #[token("f32")]
    F32,
    #[token("f64")]
    F64,
    #[regex("-?[0-9]+", |lexer| lexer.slice().parse())]
    IntValue(i64),
    #[regex("-?[0-9]+\\.[0-9]+", |lex| lex.slice().parse())]
    FloatValue(f64),
    #[regex(r#""[^"]*""#, |lexer| lexer.slice()[1..(lexer.slice().len()-1)].to_owned())]
    STRING(String),
    #[token("=")]
    ASSIGN,
    #[token("+")]
    PLUS,
    #[token("-")]
    MINUS,
    #[token("/")]
    SLASH,
    #[token("*")]
    ASTERISK,
    #[token(".")]
    DOT,
    #[token("<")]
    LT,
    #[token(">")]
    GT,
    #[token("!")]
    BANG,
    #[token(",")]
    COMMA,
    #[token(":")]
    COLON,
    #[token(";")]
    SEMICOLON,
    #[token("(")]
    LPAREN,
    #[token(")")]
    RPAREN,
    #[token("{")]
    LBRACE,
    #[token("}")]
    RBRACE,
    #[token("|")]
    PIPE,
    #[token("class")]
    CLASS,
    #[token("struct")]
    STRUCT,
    #[token("public")]
    PUBLIC,
    #[token("private")]
    PRIVATE,
    #[token("extended")]
    EXTENDED,
    #[token("function")]
    FUNCTION,
    #[token("let")]
    VAR,
    #[token("if")]
    IF,
    #[token("else")]
    ELSE,
    #[token("return")]
    RETURN,
    #[token("true")]
    TRUE,
    #[token("false")]
    FALSE,
    #[token("==")]
    EQ,
    #[token("&&")]
    AND,
    #[token("||")]
    OR,
    #[token(" ")]
    SPACE,
    #[token("\n")]
    LINE_BREAK,
    #[token("!=")]
    NOT_EQ,
}
